name: deploy-auth

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker -t edunicastro/auth built .
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push edunicastro/auth
