name: deploy-auth

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t edunicastro/auth .
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker push edunicastro/auth
